module

-- Retain genuine proof bodies for every local development module.
import all RoughRegime
import all RoughRegime.AdmissibleComparisonUniform
import all RoughRegime.AdmissibleExperimentComparison
import all RoughRegime.AdmissibleExperimentKernel
import all RoughRegime.AdmissibleExperimentTarget
import all RoughRegime.AdmissibleGridChoice
import all RoughRegime.AdmissibleGridPrior
import all RoughRegime.AdmissibleIntegrandGerm
import all RoughRegime.AdmissibleLikelihoodMean
import all RoughRegime.AdmissiblePhaseComparison
import all RoughRegime.AdmissiblePhaseExperiment
import all RoughRegime.AdmissiblePhaseLikelihood
import all RoughRegime.AdmissiblePhasePair
import all RoughRegime.AdmissiblePointwiseKernel
import all RoughRegime.AdmissiblePoissonComparison
import all RoughRegime.AdmissiblePriorTargets
import all RoughRegime.AdmissibleProductPoisson
import all RoughRegime.AdmissibleProductTargets
import all RoughRegime.AdmissibleReduction
import all RoughRegime.AdmissibleReductionNumerics
import all RoughRegime.AdmissibleReductionSequence
import all RoughRegime.AdmissibleReductionTesting
import all RoughRegime.AdmissibleScaleParameters
import all RoughRegime.AdmissibleSelectedData
import all RoughRegime.AffineJets
import all RoughRegime.AffinePathUniform
import all RoughRegime.AffineResponseLower
import all RoughRegime.AffineResponseUniform
import all RoughRegime.AffineRisk
import all RoughRegime.AliasPatterns
import all RoughRegime.AnalyticCoefficients
import all RoughRegime.AngularLaw
import all RoughRegime.AngularReciprocal
import all RoughRegime.ApplicationConditionalWald
import all RoughRegime.ApplicationConditionalWaldBracket
import all RoughRegime.ApplicationConditionalWaldEmbedding
import all RoughRegime.ApplicationEffectTransfers
import all RoughRegime.ApplicationEffects
import all RoughRegime.ApplicationEtaMAR
import all RoughRegime.ApplicationEtaTreatment
import all RoughRegime.ApplicationEtaWald
import all RoughRegime.ApplicationMAR
import all RoughRegime.ApplicationMARBracket
import all RoughRegime.ApplicationMARClass
import all RoughRegime.ApplicationMARRange
import all RoughRegime.ApplicationMARUpper
import all RoughRegime.ApplicationNormalizedMAR
import all RoughRegime.ApplicationOverlapAffine
import all RoughRegime.ApplicationOverlapBaseline
import all RoughRegime.ApplicationOverlapBounds
import all RoughRegime.ApplicationOverlapBracket
import all RoughRegime.ApplicationOverlapClass
import all RoughRegime.ApplicationOverlapCoefficientBound
import all RoughRegime.ApplicationOverlapDiagonalLower
import all RoughRegime.ApplicationOverlapExtras
import all RoughRegime.ApplicationOverlapFamilies
import all RoughRegime.ApplicationOverlapHolder
import all RoughRegime.ApplicationOverlapHolderCounterexample
import all RoughRegime.ApplicationOverlapHolderLaw
import all RoughRegime.ApplicationOverlapIndependentLower
import all RoughRegime.ApplicationOverlapParametric
import all RoughRegime.ApplicationOverlapProjection
import all RoughRegime.ApplicationOverlapReduction
import all RoughRegime.ApplicationOverlapScale
import all RoughRegime.ApplicationOverlapSelected
import all RoughRegime.ApplicationOverlapSmoothBracket
import all RoughRegime.ApplicationOverlapSmoothDiagonalLower
import all RoughRegime.ApplicationOverlapSmoothIndependentLower
import all RoughRegime.ApplicationOverlapSmoothParametric
import all RoughRegime.ApplicationOverlapSpatial
import all RoughRegime.ApplicationOverlapStatistical
import all RoughRegime.ApplicationOverlapUpper
import all RoughRegime.ApplicationPolynomialConsequences
import all RoughRegime.ApplicationProductClass
import all RoughRegime.ApplicationSeparatedBrackets
import all RoughRegime.ApplicationSeparatedEstimator
import all RoughRegime.ApplicationSeparatedLogRisk
import all RoughRegime.ApplicationSeparatedMAR
import all RoughRegime.ApplicationSeparatedMinimax
import all RoughRegime.ApplicationSeparatedPilot
import all RoughRegime.ApplicationSeparatedTreatment
import all RoughRegime.ApplicationSeparatedTreatmentUpper
import all RoughRegime.ApplicationSeparatedUpper
import all RoughRegime.ApplicationSmoothDensity
import all RoughRegime.ApplicationTransport
import all RoughRegime.ApplicationTreatmentUpper
import all RoughRegime.ApplicationTrial
import all RoughRegime.ApplicationTrialBrackets
import all RoughRegime.ApplicationTrialClass
import all RoughRegime.ApplicationWald
import all RoughRegime.ApplicationWaldBracket
import all RoughRegime.ApplicationWaldEmbedding
import all RoughRegime.Applications
import all RoughRegime.ApplicationsPilot
import all RoughRegime.ApplicationsRisk
import all RoughRegime.ApplicationsTransfers
import all RoughRegime.BaseDesign
import all RoughRegime.BasePolynomial
import all RoughRegime.BaselineScores
import all RoughRegime.BilinearDerivative
import all RoughRegime.BlockConstantReduction
import all RoughRegime.BlockProjectionEnergy
import all RoughRegime.BoxConvolution
import all RoughRegime.BoxKernel
import all RoughRegime.BracketCombination
import all RoughRegime.BracketRateConsequences
import all RoughRegime.CanonicalAdmissibility
import all RoughRegime.CanonicalCenteredTargets
import all RoughRegime.CanonicalDensityGrowth
import all RoughRegime.CanonicalHolder
import all RoughRegime.CanonicalKHolder
import all RoughRegime.CanonicalLattice
import all RoughRegime.CanonicalMeasurability
import all RoughRegime.CanonicalModelPrior
import all RoughRegime.CanonicalObservation
import all RoughRegime.CanonicalOutside
import all RoughRegime.CanonicalPairMarks
import all RoughRegime.CanonicalPairedMixtures
import all RoughRegime.CanonicalPartitionPPP
import all RoughRegime.CanonicalPhaseField
import all RoughRegime.CanonicalPoissonComparison
import all RoughRegime.CanonicalPoissonData
import all RoughRegime.CanonicalPoissonMixtures
import all RoughRegime.CanonicalPriorTargets
import all RoughRegime.CanonicalSelectedModelPrior
import all RoughRegime.CanonicalTesting
import all RoughRegime.Cauchy
import all RoughRegime.CausalConditional
import all RoughRegime.CausalConditionalBayes
import all RoughRegime.CausalConditionalComplier
import all RoughRegime.CausalConditionalTreatment
import all RoughRegime.CausalConditionalWald
import all RoughRegime.CausalConditionalWaldWitness
import all RoughRegime.CausalHomogeneity
import all RoughRegime.CausalIV
import all RoughRegime.CausalIVBalanced
import all RoughRegime.CausalIVConditional
import all RoughRegime.CausalIVOneSided
import all RoughRegime.CausalMAR
import all RoughRegime.CausalOverlap
import all RoughRegime.CausalPotentialRange
import all RoughRegime.CausalRealArmMean
import all RoughRegime.CausalRealConditionalWald
import all RoughRegime.CausalRealConditionalWaldWitness
import all RoughRegime.CausalRealIV
import all RoughRegime.CausalRealOverlap
import all RoughRegime.CausalRealTreatment
import all RoughRegime.CausalRealTrial
import all RoughRegime.CausalRealWaldWeights
import all RoughRegime.CausalTreatment
import all RoughRegime.CausalTreatmentClass
import all RoughRegime.CausalWald
import all RoughRegime.CausalWaldClass
import all RoughRegime.CausalWaldWeights
import all RoughRegime.Centering
import all RoughRegime.CoefficientFourier
import all RoughRegime.CombinedAnalytic
import all RoughRegime.CombinedPolynomial
import all RoughRegime.CompactBaseApproximation
import all RoughRegime.CompactDensityParameters
import all RoughRegime.CompactDesignComponents
import all RoughRegime.CompactDesignConstants
import all RoughRegime.CompactGradientConstants
import all RoughRegime.CompactIntervalRates
import all RoughRegime.CompactJets
import all RoughRegime.CompactKernelExpressions
import all RoughRegime.CompactKernelUniform
import all RoughRegime.CompactModelPolynomialControls
import all RoughRegime.CompactParametricNumerics
import all RoughRegime.CompactProjectionBias
import all RoughRegime.CompactProjectionComponents
import all RoughRegime.CompactRealConstants
import all RoughRegime.CompactUpperNumerics
import all RoughRegime.CompactUpperRefinements
import all RoughRegime.ComplexDerivativeBridge
import all RoughRegime.ComplexGram
import all RoughRegime.ComplexKernel
import all RoughRegime.ComplexPolynomialKernel
import all RoughRegime.Conditional
import all RoughRegime.ConditionalExamples
import all RoughRegime.ConditionalWaldSmoothBracket
import all RoughRegime.CovariateObservables
import all RoughRegime.CubeAE
import all RoughRegime.CubeObservableExtension
import all RoughRegime.CubeTransport
import all RoughRegime.DePoissonization
import all RoughRegime.DerivativeSymmetry
import all RoughRegime.DesignBessel
import all RoughRegime.DesignCells
import all RoughRegime.DesignChildBlocks
import all RoughRegime.DesignComplexBounds
import all RoughRegime.DesignDyadicPopulation
import all RoughRegime.DesignFiniteStatistics
import all RoughRegime.DesignGram
import all RoughRegime.DesignHilbert
import all RoughRegime.DesignMoments
import all RoughRegime.DesignParentCells
import all RoughRegime.DesignPolynomial
import all RoughRegime.DesignProjection
import all RoughRegime.DesignReferenceMatrices
import all RoughRegime.DesignStatistics
import all RoughRegime.DesignWeightedChildren
import all RoughRegime.DesignWeightedMoments
import all RoughRegime.DeterministicEstimatorRisk
import all RoughRegime.DiagonalIntegrand
import all RoughRegime.DisjointHolder
import all RoughRegime.DyadicApproximation
import all RoughRegime.DyadicChildren
import all RoughRegime.DyadicCollars
import all RoughRegime.DyadicDesign
import all RoughRegime.DyadicFiniteBasis
import all RoughRegime.DyadicFiniteDesign
import all RoughRegime.DyadicGeometry
import all RoughRegime.DyadicIntegral
import all RoughRegime.DyadicPackedDesign
import all RoughRegime.DyadicParentSpaces
import all RoughRegime.DyadicPartition
import all RoughRegime.DyadicRefinement
import all RoughRegime.DyadicSelection
import all RoughRegime.DyadicTensor
import all RoughRegime.DyadicTensorCollars
import all RoughRegime.DyadicTransport
import all RoughRegime.DyadicTree
import all RoughRegime.DyadicUniform
import all RoughRegime.FinitePairPlacement
import all RoughRegime.Foundation
import all RoughRegime.FuzzyRandomized
import all RoughRegime.FuzzyTesting
import all RoughRegime.GammaBounds
import all RoughRegime.GammaSeriesBound
import all RoughRegime.GammaSignBridge
import all RoughRegime.GateExpectation
import all RoughRegime.GateLaw
import all RoughRegime.GateRoot
import all RoughRegime.GeneralTesting
import all RoughRegime.GlobalAffine
import all RoughRegime.GlobalHolderIdentity
import all RoughRegime.GlobalKComposition
import all RoughRegime.GlobalKProfiles
import all RoughRegime.GlobalLattice
import all RoughRegime.GlobalLatticeMass
import all RoughRegime.GlobalNonlinearTarget
import all RoughRegime.GlobalPriorTarget
import all RoughRegime.GlobalProduct
import all RoughRegime.GlobalProfileHolder
import all RoughRegime.GlobalTargetTaylor
import all RoughRegime.GridBoundary
import all RoughRegime.GridHolder
import all RoughRegime.GridIntegral
import all RoughRegime.GridPairMass
import all RoughRegime.GridPilotLaw
import all RoughRegime.GridRegion
import all RoughRegime.HadamardSmooth
import all RoughRegime.HermitianDenominator
import all RoughRegime.HeterogeneousKernels
import all RoughRegime.HierarchicalDerivativeSums
import all RoughRegime.HierarchicalPhases
import all RoughRegime.HierarchicalSums
import all RoughRegime.HilbertGram
import all RoughRegime.HilbertInclusion
import all RoughRegime.HolderAffine
import all RoughRegime.HolderCalculus
import all RoughRegime.HolderComparison
import all RoughRegime.HolderComposition
import all RoughRegime.HolderConstants
import all RoughRegime.HolderFiniteAffine
import all RoughRegime.HolderFiniteComparison
import all RoughRegime.HolderFiniteLinear
import all RoughRegime.HolderGeometry
import all RoughRegime.HolderModulus
import all RoughRegime.HolderQuotient
import all RoughRegime.HolderRegularity
import all RoughRegime.HolderTaylorApproximation
import all RoughRegime.HolderTaylorLine
import all RoughRegime.HolderTensor
import all RoughRegime.IIDPolynomialEstimator
import all RoughRegime.IndependentPriorVariance
import all RoughRegime.IntegrandGerm
import all RoughRegime.IntroLogRefinement
import all RoughRegime.JetComposition
import all RoughRegime.KernelExpressionFinite
import all RoughRegime.KernelExpressions
import all RoughRegime.KernelMixtures
import all RoughRegime.KernelNeighborhood
import all RoughRegime.KernelNeighborhoodLocal
import all RoughRegime.KernelSeedBridge
import all RoughRegime.KernelTransfers
import all RoughRegime.KernelUniform
import all RoughRegime.Lattice
import all RoughRegime.LatticeConstruction
import all RoughRegime.LatticeCutoffs
import all RoughRegime.LatticeFourier
import all RoughRegime.LatticeGamma
import all RoughRegime.LatticeHolder
import all RoughRegime.LatticePenalties
import all RoughRegime.LatticePhaseField
import all RoughRegime.LatticePreparation
import all RoughRegime.LatticeScales
import all RoughRegime.LatticeSeparation
import all RoughRegime.LiftTranslation
import all RoughRegime.LiftVariance
import all RoughRegime.LocalLowerData
import all RoughRegime.LocalProjectionApproximation
import all RoughRegime.LocalProjectionFullApproximation
import all RoughRegime.Localization
import all RoughRegime.Lower
import all RoughRegime.LowerMeasure
import all RoughRegime.MARAugmentableLower
import all RoughRegime.MARBaseline
import all RoughRegime.MARConstantPath
import all RoughRegime.MARLocalized
import all RoughRegime.MARParametric
import all RoughRegime.MARParametricSmooth
import all RoughRegime.MARSmoothLower
import all RoughRegime.MARSourceGerms
import all RoughRegime.MARSourceMembership
import all RoughRegime.MARSourceMoments
import all RoughRegime.MARSourceSmooth
import all RoughRegime.MainLowerAssembly
import all RoughRegime.MarkRegrouping
import all RoughRegime.MarkedGamma
import all RoughRegime.MatrixDeterminant
import all RoughRegime.MatrixKernel
import all RoughRegime.MatrixUpper
import all RoughRegime.MeasureScores
import all RoughRegime.ModeExpansion
import all RoughRegime.ModePatterns
import all RoughRegime.Model
import all RoughRegime.ModelBaseEstimator
import all RoughRegime.ModelBaseLemma
import all RoughRegime.ModelBasicUpper
import all RoughRegime.ModelCompactProductRates
import all RoughRegime.ModelCompactUpper
import all RoughRegime.ModelCompactUpperCore
import all RoughRegime.ModelDegenerateMean
import all RoughRegime.ModelEstimatorCombination
import all RoughRegime.ModelEstimatorControls
import all RoughRegime.ModelEventualHardness
import all RoughRegime.ModelFullLocalPolynomials
import all RoughRegime.ModelIncrementSize
import all RoughRegime.ModelLipschitzCombination
import all RoughRegime.ModelLocalApproximation
import all RoughRegime.ModelLocalEstimator
import all RoughRegime.ModelLocalLemma
import all RoughRegime.ModelLower
import all RoughRegime.ModelLowerConsequences
import all RoughRegime.ModelMainLowerConsequences
import all RoughRegime.ModelOrientedEstimator
import all RoughRegime.ModelParametricEstimator
import all RoughRegime.ModelPilotLower
import all RoughRegime.ModelPredicates
import all RoughRegime.ModelProductEstimator
import all RoughRegime.ModelProductRates
import all RoughRegime.ModelRateConstants
import all RoughRegime.ModelReverseRisk
import all RoughRegime.ModelSourceHardness
import all RoughRegime.ModelSwap
import all RoughRegime.ModelTargetCongruence
import all RoughRegime.ModelUpper
import all RoughRegime.ModelUpperConsequences
import all RoughRegime.MultiIndexHolder
import all RoughRegime.BoundaryRegularity
import all RoughRegime.CoordinateJets
import all RoughRegime.NativeSignBridge
import all RoughRegime.NearlyUniformDesign
import all RoughRegime.NormalizedOrientedPilotEstimator
import all RoughRegime.NormalizedPilotEstimator
import all RoughRegime.ObservableMeanUpper
import all RoughRegime.OddPriorMean
import all RoughRegime.OddTaylor
import all RoughRegime.OddTaylorDerivative
import all RoughRegime.OddTaylorUniform
import all RoughRegime.OptionPartition
import all RoughRegime.OrdinaryGammaNorm
import all RoughRegime.OutsideAugmentation
import all RoughRegime.PairedGrid
import all RoughRegime.PairedTarget
import all RoughRegime.ParametricBaselineLower
import all RoughRegime.ParametricJets
import all RoughRegime.PartitionPoisson
import all RoughRegime.PatternIntegrals
import all RoughRegime.PhaseCancellation
import all RoughRegime.PhaseDerivatives
import all RoughRegime.PhaseField
import all RoughRegime.PhaseFieldPriorTransport
import all RoughRegime.PhaseFieldTransport
import all RoughRegime.PhaseInputs
import all RoughRegime.PhaseNormBounds
import all RoughRegime.PilotConcentration
import all RoughRegime.PilotConditionalRisk
import all RoughRegime.PilotHalfSamples
import all RoughRegime.PilotRateBounds
import all RoughRegime.PilotSampleSplit
import all RoughRegime.PointwiseProjectionGradient
import all RoughRegime.PoissonComparison
import all RoughRegime.PoissonCountProduct
import all RoughRegime.PoissonInterleaving
import all RoughRegime.PoissonKernelMixtures
import all RoughRegime.PoissonKernels
import all RoughRegime.PoissonLabelMarks
import all RoughRegime.PoissonLabeling
import all RoughRegime.PoissonMarkMaps
import all RoughRegime.PoissonMeasure
import all RoughRegime.PoissonMinimaxReduction
import all RoughRegime.PoissonMixtures
import all RoughRegime.PoissonNormalization
import all RoughRegime.PoissonPairProducts
import all RoughRegime.PoissonPermutation
import all RoughRegime.PoissonPhase
import all RoughRegime.PoissonPhysicalComparison
import all RoughRegime.PoissonProcess
import all RoughRegime.PoissonSampling
import all RoughRegime.PoissonSeriesBounds
import all RoughRegime.PoissonShuffleWeights
import all RoughRegime.PoissonSpectral
import all RoughRegime.PoissonSuperposition
import all RoughRegime.PoissonUniformComparison
import all RoughRegime.PoissonWordCounts
import all RoughRegime.PolynomialCells
import all RoughRegime.PolynomialDerivatives
import all RoughRegime.PolynomialDimensionOne
import all RoughRegime.PolynomialExpansion
import all RoughRegime.PolynomialLp
import all RoughRegime.PolynomialSpace
import all RoughRegime.PowerSeriesAnalytic
import all RoughRegime.Prediction
import all RoughRegime.PredictorUniformBracket
import all RoughRegime.PredictorUniformConstants
import all RoughRegime.PredictorUniformParametric
import all RoughRegime.PredictorUniformSmooth
import all RoughRegime.ProductBaselines
import all RoughRegime.ProductBrackets
import all RoughRegime.ProductClass
import all RoughRegime.ProductDensityFintype
import all RoughRegime.ProductDerivedLower
import all RoughRegime.ProductDerivedSmoothLower
import all RoughRegime.ProductDeterminationLower
import all RoughRegime.ProductDeterminationSmoothLower
import all RoughRegime.ProductFullBrackets
import all RoughRegime.ProductHardVariance
import all RoughRegime.ProductMoments
import all RoughRegime.ProductPrediction
import all RoughRegime.ProductResponseBaselines
import all RoughRegime.ProductSmoothBrackets
import all RoughRegime.ProductTarget
import all RoughRegime.ProductTesting
import all RoughRegime.ProductVarianceConvergence
import all RoughRegime.ProductVarianceHardness
import all RoughRegime.ProductVarianceIdentities
import all RoughRegime.ProductVarianceSmoothHardness
import all RoughRegime.ProductVarianceUpper
import all RoughRegime.ProfileJets
import all RoughRegime.ProfileJetsFamily
import all RoughRegime.ProjectionApproximation
import all RoughRegime.ProjectionBias
import all RoughRegime.ProjectionComplex
import all RoughRegime.ProjectionComplexBounds
import all RoughRegime.ProjectionError
import all RoughRegime.ProjectionFrame
import all RoughRegime.ProjectionFullGradient
import all RoughRegime.ProjectionGram
import all RoughRegime.ProjectionIncrementComplex
import all RoughRegime.ProjectionIncrementError
import all RoughRegime.ProjectionIncrementGradient
import all RoughRegime.ProjectionIncrementHolder
import all RoughRegime.ProjectionIncrementPolynomial
import all RoughRegime.ProjectionLevelBias
import all RoughRegime.ProjectionPolynomial
import all RoughRegime.ProjectionTelescope
import all RoughRegime.RateCombination
import all RoughRegime.RateConsequences
import all RoughRegime.RateIntervalIdentities
import all RoughRegime.RatePolynomialConsequences
import all RoughRegime.Rates
import all RoughRegime.RatioBracket
import all RoughRegime.RatioRisk
import all RoughRegime.ReciprocalComposition
import all RoughRegime.RectangleComposition
import all RoughRegime.RectanglePolynomials
import all RoughRegime.RectangleTransport
import all RoughRegime.ReductionAbstractScales
import all RoughRegime.ReductionAmplitudes
import all RoughRegime.ReductionHardness
import all RoughRegime.ReductionLogScales
import all RoughRegime.ReductionNaturalScales
import all RoughRegime.ReductionRawHardness
import all RoughRegime.ReductionScaleLimits
import all RoughRegime.ReductionScales
import all RoughRegime.ReductionSeparation
import all RoughRegime.ReductionTestingScale
import all RoughRegime.RemainingGap
import all RoughRegime.RhoPerturbation
import all RoughRegime.RhoScaling
import all RoughRegime.RiskBridge
import all RoughRegime.RoughScaleDecay
import all RoughRegime.SampleMeanBound
import all RoughRegime.SamplingDecay
import all RoughRegime.ScalarDenominator
import all RoughRegime.ScalarExponentialTail
import all RoughRegime.ScalarHolder
import all RoughRegime.ScalarIncrement
import all RoughRegime.ScoreCovariance
import all RoughRegime.Scores
import all RoughRegime.SecondOrderRemainder
import all RoughRegime.SelectorDerivatives
import all RoughRegime.SelectorFrechet
import all RoughRegime.Separated
import all RoughRegime.SeparatedLogRisk
import all RoughRegime.SeparatedMARLower
import all RoughRegime.SeparatedMARParametricSmooth
import all RoughRegime.SeparatedMARPath
import all RoughRegime.SeparatedMARSmoothLower
import all RoughRegime.SeparatedMARSource
import all RoughRegime.SeparatedMARSourceSmooth
import all RoughRegime.SeparatedTreatmentConstant
import all RoughRegime.SeparatedTreatmentEmbedding
import all RoughRegime.SeparatedTreatmentLower
import all RoughRegime.SeparatedTreatmentMoments
import all RoughRegime.SeparatedTreatmentParametric
import all RoughRegime.SeparatedTreatmentPilot
import all RoughRegime.SeparatedTreatmentRisk
import all RoughRegime.SeparatedTreatmentSmoothLower
import all RoughRegime.SeparatedTreatmentSmoothTransfers
import all RoughRegime.SeriesBounds
import all RoughRegime.SignPrior
import all RoughRegime.SincDecay
import all RoughRegime.SincSupport
import all RoughRegime.SmoothBracketTools
import all RoughRegime.SmoothCompactIntegral
import all RoughRegime.SmoothDensityLower
import all RoughRegime.SmoothDensityParametric
import all RoughRegime.SmoothGridPilot
import all RoughRegime.SmoothPilotFull
import all RoughRegime.SoftDigits
import all RoughRegime.SourceAdmissibility
import all RoughRegime.SourceAmplitude
import all RoughRegime.SourceAmplitudeGrid
import all RoughRegime.SourceAnalyticParameters
import all RoughRegime.SourceAxisHolder
import all RoughRegime.SourceBands
import all RoughRegime.SourceBlockConstant
import all RoughRegime.SourceBlockConstantLower
import all RoughRegime.SourceBlockConstantModel
import all RoughRegime.SourceBlockConstantParameters
import all RoughRegime.SourceBlockConstantPoisson
import all RoughRegime.SourceBlockConstantStatistics
import all RoughRegime.SourceCoefficientIdentity
import all RoughRegime.SourceCoefficients
import all RoughRegime.SourceConcentration
import all RoughRegime.SourceDensityMargins
import all RoughRegime.SourceDiagonalModel
import all RoughRegime.SourceDiagonalWeights
import all RoughRegime.SourceExtraConditions
import all RoughRegime.SourceFamilyFixedScores
import all RoughRegime.SourceFinalModel
import all RoughRegime.SourceFinalScales
import all RoughRegime.SourceFineGain
import all RoughRegime.SourceFineResolution
import all RoughRegime.SourceFixedOffsetLower
import all RoughRegime.SourceFrame
import all RoughRegime.SourceGamma
import all RoughRegime.SourceGapBudgets
import all RoughRegime.SourceGermHolder
import all RoughRegime.SourceGermUniform
import all RoughRegime.SourceGrid
import all RoughRegime.SourceIntervals
import all RoughRegime.SourceLatticePriors
import all RoughRegime.SourceLiteralCoefficients
import all RoughRegime.SourceLiteralFrame
import all RoughRegime.SourceLiteralPriorReindex
import all RoughRegime.SourceLocalizationBudgets
import all RoughRegime.SourceModel
import all RoughRegime.SourceModelLattice
import all RoughRegime.SourceModelWeights
import all RoughRegime.SourceNondegenerate
import all RoughRegime.SourceNonlinearGap
import all RoughRegime.SourcePoissonBudgets
import all RoughRegime.SourcePriorReindex
import all RoughRegime.SourceProductTargetIdentity
import all RoughRegime.SourceProfileHolder
import all RoughRegime.SourceProfileHolderFamily
import all RoughRegime.SourceProfileJets
import all RoughRegime.SourceProfileJetsFamily
import all RoughRegime.SourceProfileRescale
import all RoughRegime.SourceProfileRescaleFamily
import all RoughRegime.SourceProjectionFullGradient
import all RoughRegime.SourceProjectionLemma
import all RoughRegime.SourceRealizationHolder
import all RoughRegime.SourceReindex
import all RoughRegime.SourceRoughLower
import all RoughRegime.SourceRoughSequence
import all RoughRegime.SourceSelectedExtras
import all RoughRegime.SourceSelectedGrid
import all RoughRegime.SourceSelectedIdentities
import all RoughRegime.SourceSelectedModel
import all RoughRegime.SourceSelectedPoisson
import all RoughRegime.SourceSelectedStatistics
import all RoughRegime.SourceSelectedVariance
import all RoughRegime.SourceSmallerWeights
import all RoughRegime.SourceStandaloneExtras
import all RoughRegime.SourceTargetSeparation
import all RoughRegime.SourceTaylorScales
import all RoughRegime.SourceUniformGamma
import all RoughRegime.SourceUniversalExtras
import all RoughRegime.SourceUnrestrictedHolder
import all RoughRegime.SourceWeights
import all RoughRegime.SpatialAffineLaw
import all RoughRegime.SpatialConditionalLaw
import all RoughRegime.SpatialContrast
import all RoughRegime.SpatialContrastLower
import all RoughRegime.SpatialContrastPath
import all RoughRegime.SpatialContrastSmooth
import all RoughRegime.SpatialInteraction
import all RoughRegime.SpatialLocalClass
import all RoughRegime.SpatialModel
import all RoughRegime.SpatialPredictionLower
import all RoughRegime.SpatialPriorMean
import all RoughRegime.SpatialScores
import all RoughRegime.SpatialSourceScores
import all RoughRegime.SpatialTargetMeasurability
import all RoughRegime.SplitBasis
import all RoughRegime.SplitInclusion
import all RoughRegime.SplitOrthonormal
import all RoughRegime.SquareBracket
import all RoughRegime.StandaloneLocalLower
import all RoughRegime.TaylorPolynomial
import all RoughRegime.TaylorSeparationScales
import all RoughRegime.TreatmentATELower
import all RoughRegime.TreatmentArmHardness
import all RoughRegime.TreatmentDensityBounds
import all RoughRegime.TreatmentEffectRange
import all RoughRegime.TreatmentFullBrackets
import all RoughRegime.TreatmentMomentPilot
import all RoughRegime.TreatmentParametricBracket
import all RoughRegime.TreatmentParametricLower
import all RoughRegime.TreatmentReverseRelations
import all RoughRegime.TreatmentSmoothLower
import all RoughRegime.TreatmentSmoothTransfers
import all RoughRegime.TrialFullBracket
import all RoughRegime.TrialSmoothBrackets
import all RoughRegime.TrialVarianceBrackets
import all RoughRegime.TrialVarianceUpper
import all RoughRegime.TrianglePowers
import all RoughRegime.UniformBaseApproximation
import all RoughRegime.UniformCube
import all RoughRegime.UniformExpressionFamily
import all RoughRegime.UniformOuterFamily
import all RoughRegime.UniformPopulationRadius
import all RoughRegime.UniformTwoPoint
import all RoughRegime.Upper
import all RoughRegime.UpperCovariance
import all RoughRegime.UpperDegreeRules
import all RoughRegime.UpperParametric
import all RoughRegime.UpperRates
import all RoughRegime.UpperSubcriticalBias
import all RoughRegime.UpperSubcriticalGeometry
import all RoughRegime.UpperSubcriticalTuning
import all RoughRegime.UpperSubcriticalVariance
import all RoughRegime.UpperTuning
import all RoughRegime.WaldSmoothBracket
import all RoughRegime.WeightedJets
import all RoughRegime.Window
import all Solution
import all NumberedClaims
public import Lean.Util.CollectAxioms

@[expose] public section
/-! Kernel dependency audit. This command fails if any theorem in the project
depends on an axiom beyond Lean/mathlib's standard logical foundations. It
also emits a machine-readable inventory of the checked theorem declarations.
Local `import all` imports retain actual project theorem bodies; the audit
checks their theorem kind, module origins, and absence of project axioms.
For external dependencies, collectAxioms uses Lean's compiler-generated
transitive axiom inventories from the pinned canonical upstream build. This
is not a replay of every private Mathlib proof body. Comparator's independent
kernel checks separately replay the selected proofs and their dependencies.
Neither the theorem count nor this check establishes coverage of the paper;
the separate correspondence and semantic reviews establish source coverage. -/

open Lean Elab Command

run_cmd do
  let env := (← getEnv).setExporting false
  let mut projectModules : Std.HashSet Nat := {}
  for mod in env.header.moduleNames do
    if mod == `RoughRegime || "RoughRegime.".isPrefixOf mod.toString ||
        mod == `Solution || mod == `NumberedClaims then
      if let some idx := env.getModuleIdx? mod then
        projectModules := projectModules.insert idx
  unless projectModules.size == 664 do
    throwError "Expected all 664 local proof modules, found {projectModules.size}"
  for mod in env.header.modules do
    if mod.module == `RoughRegime || "RoughRegime.".isPrefixOf mod.module.toString ||
        mod.module == `Solution || mod.module == `NumberedClaims then
      unless mod.importAll do
        throwError "Project proof bodies unavailable without import all: {mod.module}"
  let isProject := fun n ↦ match env.getModuleIdxFor? n with
    | some idx => projectModules.contains idx
    | none => false
  -- These are the exported aliases named by comparator.json. Require their
  -- presence and theorem kind before auditing their full proof dependencies.
  for n in #[`RoughRegimeSubmission.mainUpper, `RoughRegimeSubmission.mainLower] do
    let some ci := env.find? n | throwError "Selected Solution theorem is missing: {n}"
    unless ci.isTheorem && isProject n do
      throwError "Selected Solution declaration is not an audited project theorem: {n}"
  for (n, ci) in env.constants.toList do
    if isProject n then
      if let .axiomInfo _ := ci then
        throwError "Project declares a custom axiom: {n}"
  let declarations := env.constants.toList.filter fun (n, ci) ↦
    isProject n && ci.isTheorem
  let declarations := declarations.toArray.qsort fun a b ↦ a.1.toString < b.1.toString
  let mut rows : Array Json := #[]
  for (n, _) in declarations do
    let axioms ← collectAxioms n
    for ax in axioms do
      unless #[`propext, `Classical.choice, `Quot.sound].contains ax do
        throwError "Unapproved axiom {ax} in {n}"
    rows := rows.push (Json.mkObj [
      ("theorem", toJson n.toString),
      ("axioms", toJson ((axioms.map Name.toString).qsort (· < ·)))])
  unless rows.size > 0 do
    throwError "The project theorem audit is empty"
  logInfo (Json.mkObj [
    ("schema_version", toJson (1 : Nat)),
    ("project_module_count", toJson projectModules.size),
    ("genuine_project_proof_bodies_loaded", toJson true),
    ("external_dependency_axiom_method", toJson "canonical upstream compiler-generated transitive axiom inventories"),
    ("theorem_count", toJson rows.size),
    ("axiom_audit_passed", toJson true),
    ("theorems", Json.arr rows)]).compress
