module

public import Mathlib


@[expose] public section
/-!
# Conditional-response identities

The conditioning information is an actual sub-sigma-algebra `m`; in the paper
it is the sigma-algebra generated by `X`. These proofs use mathlib's conditional
expectation rather than postulating the pull-out or total-expectation laws.
-/

noncomputable section

namespace RoughRegime.Conditional

open MeasureTheory

variable {Ω : Type*} {m mΩ : MeasurableSpace Ω} {μ : Measure Ω}

theorem integral_mul_condExp (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)]
    (f g : Ω → ℝ) (hf : Integrable f μ)
    (hg : StronglyMeasurable[m] g) (hfg : Integrable (f * g) μ) :
    (∫ x, f x * g x ∂μ) = ∫ x, (μ[f | m]) x * g x ∂μ := by
  calc
    _ = ∫ x, (μ[f * g | m]) x ∂μ := (integral_condExp hm).symm
    _ = _ := integral_congr_ae (condExp_mul_of_stronglyMeasurable_right hg hfg hf)

/-- The observed augmented moment has precisely the mixed-bias form. -/
theorem observed_mixed_bias (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)]
    (D U V w a b ac bc : Ω → ℝ)
    (hD : Integrable D μ) (hU : Integrable U μ) (hV : Integrable V μ)
    (hac : StronglyMeasurable[m] ac) (hbc : StronglyMeasurable[m] bc)
    (hUbc : Integrable (U * bc) μ) (hVac : Integrable (V * ac) μ)
    (hDacbc : Integrable (D * (ac * bc)) μ)
    (hmD : μ[D | m] =ᵐ[μ] w)
    (hmU : μ[U | m] =ᵐ[μ] w * a)
    (hmV : μ[V | m] =ᵐ[μ] w * b)
    (hwab : Integrable (fun x ↦ w x * a x * b x) μ) :
    (∫ x, U x * bc x + V x * ac x - D x * (ac x * bc x) ∂μ) -
      (∫ x, w x * a x * b x ∂μ) =
      -(∫ x, w x * (ac x - a x) * (bc x - b x) ∂μ) := by
  have hiU : (∫ x, U x * bc x ∂μ) = ∫ x, w x * a x * bc x ∂μ := by
    rw [integral_mul_condExp hm U bc hU hbc hUbc]
    apply integral_congr_ae
    filter_upwards [hmU] with x hx
    rw [hx]
    rfl
  have hiV : (∫ x, V x * ac x ∂μ) = ∫ x, w x * b x * ac x ∂μ := by
    rw [integral_mul_condExp hm V ac hV hac hVac]
    apply integral_congr_ae
    filter_upwards [hmV] with x hx
    rw [hx]
    rfl
  have hiD : (∫ x, D x * (ac x * bc x) ∂μ) = ∫ x, w x * (ac x * bc x) ∂μ := by
    calc
      _ = ∫ x, (μ[D | m]) x * (ac x * bc x) ∂μ := by
        simpa only [Pi.mul_apply] using
          integral_mul_condExp hm D (ac * bc) hD (hac.mul hbc) hDacbc
      _ = _ := by
        apply integral_congr_ae
        filter_upwards [hmD] with x hx
        rw [hx]
  have hiUc : Integrable (fun x ↦ w x * a x * bc x) μ := by
    have h := integrable_condExp (μ := μ) (m := m) (f := U * bc)
    have h' := h.congr (condExp_mul_of_stronglyMeasurable_right hbc hUbc hU)
    exact h'.congr (hmU.mono fun x hx ↦ by
      change (μ[U | m]) x * bc x = w x * a x * bc x
      rw [hx]
      rfl)
  have hiVc : Integrable (fun x ↦ w x * b x * ac x) μ := by
    have h := integrable_condExp (μ := μ) (m := m) (f := V * ac)
    have h' := h.congr (condExp_mul_of_stronglyMeasurable_right hac hVac hV)
    exact h'.congr (hmV.mono fun x hx ↦ by
      change (μ[V | m]) x * ac x = w x * b x * ac x
      rw [hx]
      rfl)
  have hiDc : Integrable (fun x ↦ w x * (ac x * bc x)) μ := by
    have h := integrable_condExp (μ := μ) (m := m) (f := D * (ac * bc))
    have h' := h.congr (condExp_mul_of_stronglyMeasurable_right (hac.mul hbc) hDacbc hD)
    exact h'.congr (hmD.mono fun x hx ↦ by
      change (μ[D | m]) x * (ac x * bc x) = w x * (ac x * bc x)
      rw [hx])
  rw [integral_sub (f := fun x ↦ U x * bc x + V x * ac x)
      (g := fun x ↦ D x * (ac x * bc x)) (hUbc.add hVac) hDacbc,
    integral_add (f := fun x ↦ U x * bc x) (g := fun x ↦ V x * ac x) hUbc hVac,
    hiU, hiV, hiD, ← integral_add hiUc hiVc,
    ← integral_sub (f := fun x ↦ w x * a x * bc x + w x * b x * ac x)
      (g := fun x ↦ w x * (ac x * bc x)) (hiUc.add hiVc) hiDc,
    ← integral_sub (f := fun x ↦ w x * a x * bc x + w x * b x * ac x - w x * (ac x * bc x))
      (g := fun x ↦ w x * a x * b x) ((hiUc.add hiVc).sub hiDc) hwab, ← integral_neg]
  apply integral_congr_ae
  filter_upwards [] with x
  ring

/-- Squared prediction loss splits into irreducible conditional variance and
the squared distance of the predictor from the conditional mean. -/
theorem prediction_loss_decomposition (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)]
    (Y f mY : Ω → ℝ) (hY : Integrable Y μ)
    (hf : StronglyMeasurable[m] f) (hmY : StronglyMeasurable[m] mY)
    (hmean : μ[Y | m] =ᵐ[μ] mY)
    (hYY : Integrable (fun x ↦ Y x ^ 2) μ)
    (hYf : Integrable (Y * f) μ) (hYm : Integrable (Y * mY) μ)
    (hff : Integrable (fun x ↦ f x ^ 2) μ)
    (hmm : Integrable (fun x ↦ mY x ^ 2) μ)
    (hmf : Integrable (mY * f) μ) :
    (∫ x, (Y x - f x) ^ 2 ∂μ) =
      (∫ x, (Y x - mY x) ^ 2 ∂μ) + (∫ x, (mY x - f x) ^ 2 ∂μ) := by
  have hiYf : (∫ x, Y x * f x ∂μ) = ∫ x, mY x * f x ∂μ := by
    rw [integral_mul_condExp hm Y f hY hf hYf]
    apply integral_congr_ae
    filter_upwards [hmean] with x hx
    rw [hx]
  have hiYm : (∫ x, Y x * mY x ∂μ) = ∫ x, mY x ^ 2 ∂μ := by
    rw [integral_mul_condExp hm Y mY hY hmY hYm]
    apply integral_congr_ae
    filter_upwards [hmean] with x hx
    rw [hx, pow_two]
  have loss_expand (A B : Ω → ℝ)
      (hAA : Integrable (fun x ↦ A x ^ 2) μ)
      (hAB : Integrable (A * B) μ) (hBB : Integrable (fun x ↦ B x ^ 2) μ) :
      (∫ x, (A x - B x) ^ 2 ∂μ) =
        (∫ x, A x ^ 2 ∂μ) - 2 * (∫ x, A x * B x ∂μ) + (∫ x, B x ^ 2 ∂μ) := by
    have he : (fun x ↦ (A x - B x) ^ 2) =
        (fun x ↦ A x ^ 2 - 2 * (A x * B x) + B x ^ 2) := by
      funext x
      ring
    have hAB' : Integrable (fun x ↦ A x * B x) μ := hAB
    have htwo : Integrable (fun x ↦ 2 * (A x * B x)) μ := hAB'.const_mul 2
    rw [he, integral_add (f := fun x ↦ A x ^ 2 - 2 * (A x * B x))
      (g := fun x ↦ B x ^ 2) (hAA.sub htwo) hBB,
      integral_sub (f := fun x ↦ A x ^ 2) (g := fun x ↦ 2 * (A x * B x)) hAA htwo,
      integral_const_mul]
  rw [loss_expand Y f hYY hYf hff, loss_expand Y mY hYY hYm hmm,
    loss_expand mY f hmm hmf hff, hiYf, hiYm]
  ring

theorem conditional_mean_minimizes_loss (hm : m ≤ mΩ) [SigmaFinite (μ.trim hm)]
    (Y f mY : Ω → ℝ) (hY : Integrable Y μ)
    (hf : StronglyMeasurable[m] f) (hmY : StronglyMeasurable[m] mY)
    (hmean : μ[Y | m] =ᵐ[μ] mY)
    (hYY : Integrable (fun x ↦ Y x ^ 2) μ)
    (hYf : Integrable (Y * f) μ) (hYm : Integrable (Y * mY) μ)
    (hff : Integrable (fun x ↦ f x ^ 2) μ)
    (hmm : Integrable (fun x ↦ mY x ^ 2) μ)
    (hmf : Integrable (mY * f) μ) :
    (∫ x, (Y x - mY x) ^ 2 ∂μ) ≤ ∫ x, (Y x - f x) ^ 2 ∂μ := by
  rw [prediction_loss_decomposition hm Y f mY hY hf hmY hmean hYY hYf hYm hff hmm hmf]
  have h : 0 ≤ ∫ x, (mY x - f x) ^ 2 ∂μ := integral_nonneg fun x ↦ sq_nonneg _
  linarith

end RoughRegime.Conditional
